import nodemailer from "nodemailer"

export async function sendCaseBrief(to: string, clientName: string, summary: string) {
    // NOTE: In a real production app, use environment variables for credentials.
    // For this demo, we check if credentials exist, otherwise we log to console.

    if (!process.env.EMAIL_SERVER_HOST) {
        console.log("====================================================")
        console.log("EMAIL SIMULATION (No Creds Provided)")
        console.log(`TO: ${to}`)
        console.log(`SUBJECT: New Case Inquiry: ${clientName}`)
        console.log("----------------------------------------------------")
        console.log(summary)
        console.log("====================================================")
        return
    }

    const transporter = nodemailer.createTransport({
        host: process.env.EMAIL_SERVER_HOST,
        port: Number(process.env.EMAIL_SERVER_PORT) || 587,
        auth: {
            user: process.env.EMAIL_SERVER_USER,
            pass: process.env.EMAIL_SERVER_PASSWORD,
        },
        secure: false, // true for 465, false for other ports
    })

    await transporter.sendMail({
        from: process.env.EMAIL_FROM || '"Chan & Co. AI" <ai@macchan.hk>',
        to,
        subject: `[AI Brief] New Case Inquiry: ${clientName}`,
        text: summary,
        html: `
      <h2>New Client Inquiry</h2>
      <p><strong>Client:</strong> ${clientName}</p>
      <hr />
      <h3>AI Case Brief</h3>
      <pre style="font-family: sans-serif; white-space: pre-wrap;">${summary}</pre>
      <hr />
      <p><em>Generated by Client Intake Portal AI</em></p>
    `,
    })
}
